version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - sqlite_data:/app/prisma
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && node scripts/create-admin.js && npm run dev"

volumes:
  sqlite_data: 